# Generated by Django 5.1.6 on 2025-03-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_book_author_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
