# Generated by Django 5.1.6 on 2025-03-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_author_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='genre',
        ),
        migrations.AddField(
            model_name='author',
            name='genre',
            field=models.ManyToManyField(to='catalog.genre'),
        ),
    ]
