# Generated by Django 5.1.6 on 2025-05-15 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_author_genre_author_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(help_text='An author for the book.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.author'),
        ),
    ]
